name: CI Pipeline for telegram-bot

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew  # 실행 권한 추가

      # 3. Build the project using Gradle (or Maven if needed)
      - name: Build with Gradle
        run: ./gradlew build -x test # If using Maven, change this to `mvn clean install`

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yanoos555/telegram-bot:${{ steps.extract_tag.outputs.TAG }}
